import { Toaster } from "sonner";
import "./globals.css";
import "./typography.scss";
import "./record.scss";
import type { Metadata } from "next";
import Header from "@/components/header/header";
import ClientBoot from "./client-boot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Toaster richColors theme="dark" position="top-right" />
      <ClientBoot>
        <body>
          <Header />
          {children}
        </body>
      </ClientBoot>
    </html>
  );
}
